name: Convert Doc Files

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "15 10 * * 2"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    env:
      USER: ${{ github.repository_owner }}
      REPO_CODE: ${{ vars.REPO_CODE }}
      PATH_CODE: code
      COUNT_DOC: ${{ vars.COUNT_DOC || 50 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check JSONL file
        run: |
          count=$(jq -c 'select((.type == ".doc" or .type == ".rtf") and .alias == null)' *.jsonl | wc -l)
          echo "Found $count matching lines"
          if [ "$count" -eq 0 ]; then
            echo "No matching lines found, exiting workflow."
            exit 0
          fi

      - name: Generate Token
        id: app-token2
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ env.USER }}
          repositories: ${{ env.REPO_CODE }}

      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          repository: ${{ env.USER }}/${{ env.REPO_CODE }}
          path: ${{ env.PATH_CODE }}
          fetch-depth: 1
          ref: ${{ github.ref }}
          token: ${{ steps.app-token2.outputs.token }}

      - name: Python Env
        uses: actions/setup-python@v6
        with:
          # python-version-file: ".python-version"
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          working-directory: ${{ env.PATH_CODE }}

      # - name: Cache APT packages
      #   uses: actions/cache@v4
      #   with:
      #     path: /var/cache/apt/archives
      #     key: ${{ runner.os }}-apt-libreoffice-writer-nogui
      #     restore-keys: |
      #       ${{ runner.os }}-apt-

      - name: Install LibreOffice
        run: |
          sudo apt-get update  -qq &&
          sudo apt-get install --no-install-recommends -y \
            libreoffice-writer-nogui > /dev/null

      - name: Verify LibreOffice version
        run: libreoffice --version

      - name: Run script page
        # if: github.event.schedule == '0 4 * * *'
        run: |
          pushd $PATH_CODE &&
          bash scripts/run-convert-docx.sh $COUNT_DOC .. &&
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update
