name: Sync Docx Files

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "10 10 * * 2"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    env:
      USER: ${{ github.repository_owner }}
      REPO_CODE: ${{ vars.REPO_CODE }}
      PATH_CODE: code
      REPO_DATA: ${{ vars.REPO_DATA }}
      PATH_DATA: data
      COUNT_DATA: ${{ vars.COUNT_DATA || 10 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate Token1
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.HPW_APP_CLIENT_ID }}
          private-key: ${{ secrets.HPW_APP_PRIVATE_KEY }}
          owner: ${{ secrets.HPW_REPO }}

      - name: Set up .netrc
        run: |
          echo "machine github.com" > ~/.netrc
          echo "login x-access-token" >> ~/.netrc
          echo "password ${{ steps.app-token.outputs.token }}" >> ~/.netrc
          chmod 600 ~/.netrc

      - name: Generate Token2
        id: app-token2
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ env.USER }}
          repositories: ${{ env.REPO_CODE }},${{ env.REPO_DATA }}

      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          repository: ${{ env.USER }}/${{ env.REPO_CODE }}
          path: ${{ env.PATH_CODE }}
          fetch-depth: 1
          ref: ${{ github.ref }}
          token: ${{ steps.app-token2.outputs.token }}

      - name: Checkout Data
        uses: actions/checkout@v6
        with:
          repository: ${{ env.USER }}/${{ env.REPO_DATA }}
          path: ${{ env.PATH_DATA }}
          fetch-depth: 1
          ref: ${{ github.ref }}
          token: ${{ steps.app-token2.outputs.token }}

      - name: Python Env
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0

      - name: Run script page
        # if: github.event.schedule == '0 4 * * *'
        run: |
          pushd $PATH_CODE &&
          bash scripts/run-dl-files-inc.sh $COUNT_DATA .. ../$PATH_DATA
          popd

      - name: Git auto commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit_message: Automated update
          # commit_options: '--no-verify --signoff'
          push_options: "--force"
          file_pattern: "*.docx, *.doc, *.rtf, *.docm, *.jsonl"
